FROM debian:bullseye

RUN apt-get update && apt-get -y upgrade && apt-get install -y curl

WORKDIR /usr/local/

RUN curl -L -o portainer.tar.gz  https://github.com/portainer/portainer/releases/download/2.32.0/portainer-2.32.0-linux-amd64.tar.gz && tar -xvzf portainer.tar.gz

CMD ["/usr/local/portainer/portainer"]